server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaccincationCenterDB
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  application:
    name: Vaccination-Center

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
      base-path: "/monitor"
      
  endpoint:
    health:
      show-details: always



